### ISSUE TITLE
Add a Slack bot

### ISSUE THREAD

**Issue by LeonorLunatech** [lunatech-labs/lunatech-chef#166]
The current lunatech-lunch-planner has a (popular!!) slack bot that every week asks each person if they are attending the planned meals.
The slack bot for lunatech-chef can be done the same way as the current one. 
The people that receive the message are actually people that did not fill the attendance in the webapp already.
When the bot runs has to be configurable, if possible by a cron expression.

Please check how the current bot is done in lunatech-lunch-planner. A new better way of doing it may be available, so do check the internet for resources

https://slack.com/help/articles/115005265703-Create-a-bot-for-your-workspace

**Comment by zanio** [comment]
This issue has been handled from another service. The Lunch-Bot is now happening from a different service

**Comment by LeonorLunatech** [comment]
Reimplemented lunchbot in https://github.com/lunatech-labs/lunatech-slackbots/pull/10

**Comment by LeonorLunatech** [comment]
Deployed version of the bot works is working (together with deployed version of lunatech-chef)
