### ISSUE TITLE
Return single, unique and most updated attendance information

### ISSUE THREAD

**Issue by zanio** [lunatech-labs/lunatech-chef#237]
When you go to the luna-chef UI, The `/whoisjoining` route and `/` both display all user attendance response for a particular meal schedule. This shouldn't be the case. It should only return the most recent user response for a particular schedule
 
`/whoisjoining`

<img width="996" alt="Screenshot 2023-03-27 at 13 50 07" src="https://user-images.githubusercontent.com/38135488/227933577-b2e4e164-4513-4b49-8e26-2d43372c2743.png">

`/`

<img width="1461" alt="Screenshot 2023-03-27 at 13 51 59" src="https://user-images.githubusercontent.com/38135488/227933866-1a6b063e-2c72-45e5-9238-bc08c4257ca8.png">

**Comment by LeonorLunatech** [comment]
Hi Ani!
If you have question about current functionality could you please clarity it with me first? I don't understand what issue you are trying to explain here.
You schedules the same meal 3 times in the same place and if in the end it aggregates the information then it is not exactly an issue

**Comment by LeonorLunatech** [comment]
I would more quickly try to fix having duplicated schedules then fixing anything else

**Comment by LeonorLunatech** [comment]
As clarified yesterday when you call the POST api method you are creating new entries in the attendance table which is the expected behavior so I am closing this issue.
